### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by anxdpanic** [anxdpanic/script.common.plugin.cache#14]

**Comment by anxdpanic** [comment]
py3 release: 
https://github.com/anxdpanic/script.common.plugin.cache/releases/tag/2.6.0
[script.common.plugin.cache-2.6.0.zip](https://github.com/anxdpanic/script.common.plugin.cache/releases/download/2.6.0/script.common.plugin.cache-2.6.0.zip)

**Comment by Linkinsoldier** [comment]
Perfect, that fixed all issues for me. Thank you very much

**Comment by anxdpanic** [comment]
Thanks for confirming, I will submit it to the official repository so it's available. Please open an issue here if you run into any more issues 👍
