### ISSUE TITLE
Update library in official repo

### ISSUE THREAD

**Issue by maxbambi** [anxdpanic/script.common.plugin.cache#18]
If your version is updated to work with python 3, why not to add it to official repo?
A lot of plugins, that work with this library, can't be added or updated on official repo, because official public version of this library (2.5.10) isn't Python 3 compatible...

**Comment by anxdpanic** [comment]
I submitted it to the official repository yesterday. Just have to wait for it to be reviewed and merged.

**Comment by anxdpanic** [comment]
This was merged into the official repository, should be available as caching allows.
