### ISSUE TITLE
 commoncache.db...this stranger....

### ISSUE THREAD

**Issue by p060477** [anxdpanic/script.common.plugin.cache#33]
hi, is there any patienceable guy who will so kind to explain to me the use and the importance of.
commoncache.db file...??
i see that is growin in its dimension..is getting bigger..so i'd like the meaning/reason why.....
and moreover if it is possible to delete it....every maintenace add on that clear the cache that i have is not able to clear it...
thxs so much in adv.!
cheers

**Comment by anxdpanic** [comment]
It's a cache that is used by add-ons (if they use this script to handle caching).
It should in most cases be fine to delete. I cannot tell you what is stored in the database--_other than cached items of some sort_--  as it will depend on the add-on(s) you have installed that are using this script.

**Comment by p060477** [comment]
thxs so much for yr reply!
and what about : 
 "why every maintenace add on that clear the cache that i have is not able to clear it ?"
thxs again
